spring:
  datasource:
    url: jdbc:mariadb://210.104.6.82:24510/Likelion
    driver-class-name: org.mariadb.jdbc.Driver
    username: Likelion
    password: likelion

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
